// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ934jINxquy5xnq5JSKj2uDeW9RbXXac',
    appId: '1:1023321331697:web:a69481559a05ad4822d650',
    messagingSenderId: '1023321331697',
    projectId: 'atelier-4-h-nasir-iir5-g2',
    authDomain: 'atelier-4-h-nasir-iir5-g2.firebaseapp.com',
    storageBucket: 'atelier-4-h-nasir-iir5-g2.appspot.com',
    measurementId: 'G-8QFB43143Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCta0jhBBleRZQEbxHROS0WXI_OmK7ZNqs',
    appId: '1:1023321331697:android:278b3650a3545d1222d650',
    messagingSenderId: '1023321331697',
    projectId: 'atelier-4-h-nasir-iir5-g2',
    storageBucket: 'atelier-4-h-nasir-iir5-g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZJu4R1eiedEeWXbnG82oa43QMqqzcIzY',
    appId: '1:1023321331697:ios:e03478119bda25f622d650',
    messagingSenderId: '1023321331697',
    projectId: 'atelier-4-h-nasir-iir5-g2',
    storageBucket: 'atelier-4-h-nasir-iir5-g2.appspot.com',
    iosBundleId: 'com.example.atelier4HNasirIir5g2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZJu4R1eiedEeWXbnG82oa43QMqqzcIzY',
    appId: '1:1023321331697:ios:5886327428b10c0d22d650',
    messagingSenderId: '1023321331697',
    projectId: 'atelier-4-h-nasir-iir5-g2',
    storageBucket: 'atelier-4-h-nasir-iir5-g2.appspot.com',
    iosBundleId: 'com.example.atelier4HNasirIir5g2.RunnerTests',
  );
}
